### ISSUE TITLE
fput doesn't work

### ISSUE THREAD

**Issue by tcmulcahy** [facebook/fb-adb#30]
(also I believe the docs are incorrect: "Retrieve a file from device." Probably should be "Store a file on the device")

This is what I get when I use it:

$ fb-adb fput /tmp/libkeyboard.so /data/local/tmp/foo.so
fb-adb fput: execvpe("/proc/self/exe"): No such file or directory

**Comment by dcolascione** [comment]
On what device?

**Comment by jbeich** [comment]
Are you on Windows or OS X? I can reproduce it with both `fb-adb fput` and `fb-adb fget` on FreeBSD where the issue disappears after mounting `/proc` filesystem _locally_.

Better not repeat **adb** mess of platform-specific code: [Windows](https://github.com/android/platform_system_core/blob/23fe7be/adb/adb.cpp#L658), [OS X](https://github.com/android/platform_system_core/blob/23fe7be/adb/get_my_path_darwin.cpp), [Linux](https://github.com/android/platform_system_core/blob/23fe7be/adb/get_my_path_linux.cpp), [FreeBSD](https://svnweb.freebsd.org/ports/head/devel/android-tools-adb/files/get_my_path_freebsd.cpp?revision=398924&view=co) while it could be generic[[1]](http://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/ports/devel/adb/patches/patch-adb_get_my_path_generic_c?rev=1.1.1.1&content-type=text/plain)[[2]](http://cvsweb.openbsd.org/cgi-bin/cvsweb/~checkout~/ports/devel/adb/patches/patch-adb_adb_c?rev=1.1.1.1&content-type=text/plain).

**Comment by dcolascione** [comment]
You mean, we can use a worse API for the sake of broken systems that are missing important APIs that happen to be accessed by calling open(2) on strings beginning with "/proc"?

I'll work around the lack of /proc/self/exe support, but I'm keeping it in the Linux case, because execing /proc/self/exe is strictly better than execing orig_argv0 when someone might be replacing the program at the same time.

**Comment by dcolascione** [comment]
Should work now. Thanks for the report.

**Comment by tcmulcahy** [comment]
Confirmed. Thanks for fixing!
